name: example
description: A project that showcases how to enable the Stokkur lints for Flutter apps.

publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  stokkur_analysis:
    path: ../
