name: stokkur_analysis
version: 0.0.1
description: Lint rules for Flutter used internally at Stokkur Software.
repository: https://github.com/jorgesarabia/stokkur_analysis
issue_tracker: https://github.com/jorgesarabia/stokkur_analysis
homepage: https://github.com/jorgesarabia/stokkur_analysis
documentation: https://github.com/jorgesarabia/stokkur_analysis


environment:
  sdk: ">=2.12.0 <3.0.0"